
services:
  completer:
    build: .
    image: lelus78/plex-library-completer:dev   # tag locale
    container_name: plex-library-completer
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5000:5000"
    volumes:
      - ./Missing_data:/app/Missing_data
      - ./Deezer_Links_Output:/app/Deezer_Links_Output
      - ./state_data:/app/state_data
      - ./templates:/app/templates
      - ./plex_playlist_sync:/app/plex_playlist_sync
      - ./app.py:/app/app.py
      - ./.env:/app/.env
      - ./config.toml:/root/.config/streamrip/config.toml
      - /mnt/m/organizzata:/downloads  # Downloads diretti alla libreria principale
      # - ./downloads:/downloads  # Downloads separati (commentato)
    restart: on-failure
